# Generated by Django 5.2.3 on 2025-06-20 15:15

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[account.models.validateforNumeric])),
                ('location', models.CharField(max_length=30, validators=[account.models.validateforNumeric])),
                ('url', models.URLField(blank=True, null=True, validators=[account.models.validateforNumeric, account.models.validateUrl])),
                ('adminEmail', models.EmailField(max_length=254, validators=[account.models.validateforNumeric])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
