# Generated by Django 5.2.3 on 2025-06-28 04:43

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_roles(apps, schema_editor):
    Role = apps.get_model('account', 'Role')
    Role.objects.get_or_create(role='Teacher')
    Role.objects.get_or_create(role='Student')
    
def reverse_default_roles(apps, schema_editor):
    Role = apps.get_model('account', 'Role')
    Role.objects.filter(role__in=['Teacher', 'Student']).delete()
    

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[account.models.validateforNumeric])),
                ('location', models.CharField(max_length=30, validators=[account.models.validateforNumeric])),
                ('url', models.URLField(blank=True, null=True, validators=[account.models.validateforNumeric, account.models.validateUrl])),
                ('adminEmail', models.EmailField(max_length=254, validators=[account.models.validateforNumeric])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
        ),
        
    migrations.RunPython(create_default_roles, reverse_default_roles)
    ]
