# Generated by Django 5.2.3 on 2025-06-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='user',
            new_name='organization',
        ),
    ]
